services:
    app:
        build:
            context: './vendor/laravel/sail/runtimes/8.4'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: 'sail-8.4/app'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            LOG_CHANNEL: 'stderr'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        command: php artisan bot:poll --timeout=25 --sleep=1
        restart: unless-stopped
networks:
    sail:
        driver: bridge
